/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-01-23 11:02:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psl.dao.ProductDaoImpl;
import com.psl.dao.ProductDao;
import com.psl.bean.Product;
import java.util.List;

public final class FinalJSP_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


public Product call(int proid){
ProductDao product =new ProductDaoImpl();
/* int max=5;
int min=1;
double random=Math.floor(Math.random() * (max + min -1)) + min;
List<Product> list=product.getProductByCategoryId(1); */
Product p=product.getProduct(proid);
return p;
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>!!!...GOGrabIT...!!!</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jq.js\"></script>\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" .affix {\r\n");
      out.write("      top: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .affix + .container-fluid {\r\n");
      out.write("      padding-top: 70px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var name;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".productclass\").click(function(){\r\n");
      out.write("\t    alert(\"Text: \" + $(this).text());\r\n");
      out.write("\t     name=$(this).text();\r\n");
      out.write("\t  window.location.href=\"Review.jsp?param=\"+name;\r\n");
      out.write("\t    \r\n");
      out.write("\t});\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var pimage;\r\n");
      out.write("var pname,pprice;\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\t loadFridge();\r\n");
      out.write(" \tloadElectronics();\r\n");
      out.write("\tloadIron();  \r\n");
      out.write("}\r\n");
      out.write("function loadFridge(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 
		for(int i=1;i<5;i++)
		 {
			System.out.println(i);
			Product pro=call(i);
			String pname=pro.getProductName();
			double pprice=pro.getProductPrice();
		
      out.write("\r\n");
      out.write("\t\tvar html = '<div class=\"col-sm-3 col-lg-3 col-md-3\" ><div class=\"thumbnail\"><img id=\"pim\" src=\"images/'+\"");
      out.print(pname);
      out.write("\"+'.jpeg\"  alt=\"\" width=\"320px\" height=\"150px\"><div class=\"caption\"><h4><a class=\"productclass\" href=\"Review.jsp?param=");
      out.print(pname);
      out.write("\" >'+\"");
      out.print(pname);
      out.write("\"+'</a></h4><h4>'+'");
      out.print(pprice);
      out.write("'+'</h4></div><div class=\"ratings\"><p><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span></p><p>15 reviews</p></div></div>';\r\n");
      out.write("\t\tvar newDiv;\r\n");
      out.write("\t\tnewDiv = document.createElement(\"DIV\");\r\n");
      out.write("\t\tnewDiv.innerHTML = html;\r\n");
      out.write("\t\t/*newDiv.id = \"field\" + itemID;*/\r\n");
      out.write("\t\tdocument.getElementById('fridge').insertBefore(newDiv,null);\r\n");
      out.write("\t");
}
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function loadElectronics(){\r\n");
      out.write("\t");
 
	for(int i=6;i<10;i++)
	 {
		System.out.println(i);
		
		Product pro=call(i);
		System.out.println(pro.getProductName());
		String pname=pro.getProductName();
		double pprice=pro.getProductPrice();
	
      out.write("\r\n");
      out.write("\tvar html = '<div class=\"col-sm-3 col-lg-3 col-md-3\" ><div class=\"thumbnail\"><img id=\"pac\" src=\"images/'+\"");
      out.print(pname);
      out.write("\"+'.jpeg\"  alt=\"\" width=\"320px\" height=\"150px\"><div class=\"caption\"><h4><a class=\"productclass\" href=\"Review.jsp?param=");
      out.print(pname);
      out.write("\" >'+\"");
      out.print(pname);
      out.write("\"+'</a></h4><h4>'+'");
      out.print(pprice);
      out.write("'+'</h4></div><div class=\"ratings\"><p><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span></p><p>15 reviews</p></div></div>';\r\n");
      out.write("\tvar newDiv;\r\n");
      out.write("\tnewDiv = document.createElement(\"DIV\");\r\n");
      out.write("\tnewDiv.innerHTML = html;\r\n");
      out.write("\t/*newDiv.id = \"field\" + itemID;*/\r\n");
      out.write("\tdocument.getElementById('ac').insertBefore(newDiv,null);\r\n");
}
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function loadIron(){\r\n");
      out.write("\t");
 
	for(int i=10;i<14;i++)
	 {
		System.out.println(i);
		Product pro=call(i);
		System.out.println(pro.getProductName());
		String pname=pro.getProductName();
		double pprice=pro.getProductPrice();
	
      out.write("\r\n");
      out.write("\tvar html = '<div class=\"col-sm-3 col-lg-3 col-md-3\" ><div class=\"thumbnail\"><img id=\"pac\" src=\"images/'+\"");
      out.print(pname);
      out.write("\"+'.jpeg\"  alt=\"\" width=\"320px\" height=\"150px\"><div class=\"caption\"><h4><a class=\"productclass\" href=\"Review.jsp?param=");
      out.print(pname);
      out.write("\" >'+\"");
      out.print(pname);
      out.write("\"+'</a></h4><h4>'+'");
      out.print(pprice);
      out.write("'+'</h4></div><div class=\"ratings\"><p><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span><span class=\"glyphicon glyphicon-star\"></span></p><p>15 reviews</p></div></div>';\r\n");
      out.write("\tvar newDiv;\r\n");
      out.write("\tnewDiv = document.createElement(\"DIV\");\r\n");
      out.write("\tnewDiv.innerHTML = html;\r\n");
      out.write("\t/*newDiv.id = \"field\" + itemID;*/\r\n");
      out.write("\tdocument.getElementById('iron').insertBefore(newDiv,null);\r\n");
}
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Facebook Login Button -->\r\n");
      out.write("<script>\r\n");
      out.write("  window.fbAsyncInit = function() {\r\n");
      out.write("    FB.init({\r\n");
      out.write("      appId      : '1098991976802112',\r\n");
      out.write("      xfbml      : true,\r\n");
      out.write("      version    : 'v2.5'\r\n");
      out.write("    });\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  (function(d, s, id){\r\n");
      out.write("     var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("     if (d.getElementById(id)) {return;}\r\n");
      out.write("     js = d.createElement(s); js.id = id;\r\n");
      out.write("     js.src = \"//connect.facebook.net/en_US/sdk.js\";\r\n");
      out.write("     fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("   }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Facebook Login Button End -->\r\n");
      out.write("\r\n");
      out.write("   <div id=\"myModalforSignup\"class=\"modal fade\">\r\n");
      out.write("              <div class=\"modal-dialog\" >\r\n");
      out.write("                     <div class=\"modal-content\">\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Header Section -->\r\n");
      out.write("                           <div class=\"modal-header\">\r\n");
      out.write("                           <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                  <h2>Sign UP</h2>\r\n");
      out.write("                                  \r\n");
      out.write("                           </div>\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Body Section -->\r\n");
      out.write("                           <div class=\"modal-body\">\r\n");
      out.write("                                  <form class=\"form col-md-12\" action=\"signup.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <input type=\"text\" class=\"form-control input-lg\" placeholder=\"First Name\" required autofocus /><br> -->\r\n");
      out.write("\t\t\t\t                        <input name=\"fname\" type=\"text\" class=\"form-control input-lg\" placeholder=\"First Name\" required autofocus /><br>\r\n");
      out.write("\t\t\t\t                         <input name=\"lname\" type=\"text\" class=\"form-control input-lg\" placeholder=\"Last Name\" required   /><br>\r\n");
      out.write("\t\t\t\t                         <input name=\"uname\" type=\"text\" class=\"form-control input-lg\" placeholder=\"User Name\" required  /><br>\r\n");
      out.write("\t\t\t\t                         <input name=\"contact\" type=\"text\" class=\"form-control input-lg\" placeholder=\"Contact No\" required  /><br>\r\n");
      out.write("                                         <input name=\"email\" type=\"text\" class=\"form-control input-lg\" placeholder=\"Email\" required  /><br>\r\n");
      out.write("                                         <input name=\"pwd\" type=\"password\" class=\"form-control input-lg\" placeholder=\"Password\" required /><br>\r\n");
      out.write("                                          <input name=\"confirmpwd\" type=\"password\" class=\"form-control input-lg\" placeholder=\"Confirm Password\" required /><br><br><br>\r\n");
      out.write("                                       \t\t<button class=\"btn btn-primary btn-lg btn-block\">Sign Up</button>\r\n");
      out.write("                                       \r\n");
      out.write("                                  </form>\r\n");
      out.write("                           </div>\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Footer Section -->\r\n");
      out.write("                           <div class=\"modal-footer\">\r\n");
      out.write("                                  \r\n");
      out.write("                           </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("       </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("       \t\r\n");
      out.write("       <!-- Modal for sign in -->\r\n");
      out.write("   <div id=\"myModal\"class=\"modal fade\">\r\n");
      out.write("              <div class=\"modal-dialog\">\r\n");
      out.write("                     <div class=\"modal-content\">\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Header Section -->\r\n");
      out.write("                           <div class=\"modal-header\">\r\n");
      out.write("                           <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                  <h2>Please sign in</h2>\r\n");
      out.write("                                   <div class=\"fb-login-button\" data-max-rows=\"1\" data-size=\"large\" data-show-faces=\"false\" data-auto-logout-link=\"false\"></div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Body Section -->\r\n");
      out.write("                           <div class=\"modal-body\">\r\n");
      out.write("                                  <form class=\"form col-md-12\" name=\"login\" method=\"post\" action=\"login.jsp\" >\r\n");
      out.write("\r\n");
      out.write("                                         <input id=\"uname\" name=\"uname\" type=\"text\" class=\"form-control input-lg\" placeholder=\"Email\" required autofocus />\r\n");
      out.write("                                         <input  id=\"pwd\" name=\"pwd\" type=\"password\" class=\"form-control input-lg\" placeholder=\"Password\" required />\r\n");
      out.write("                                        \r\n");
      out.write("                                         <label class=\"checkbox\"> <input type=\"checkbox\"\r\n");
      out.write("                                                value=\"remember-me\" /> Remember me\r\n");
      out.write("                                         </label>\r\n");
      out.write("                                        \r\n");
      out.write("                                         <button class=\"btn btn-primary btn-lg btn-block\">Sign In</button>\r\n");
      out.write("                                         <label name=\"status\"></label>\r\n");
      out.write("                                  </form>\r\n");
      out.write("                           </div>\r\n");
      out.write("                          \r\n");
      out.write("                           <!-- Footer Section -->\r\n");
      out.write("                           <div class=\"modal-footer\">\r\n");
      out.write("                                  <div class=\"col-md-12\">\r\n");
      out.write("                                         <span class=\"pull-left\"><a href=\"#\">Forgot Password?</a></span>\r\n");
      out.write("                                         <span><a href=\"#\">Register</a></span>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\" >\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("  \r\n");
      out.write(" \t<div class=\"col-md-5\">\r\n");
      out.write("    <img src=\"images/logo.png\"width=\"30%\" height=\"30%\">\r\n");
      out.write(" \t</div>     \r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <input type=\"search\"  class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("        <div class=\"input-group-btn\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-default\" >\r\n");
      out.write("                <span class=\"glyphicon glyphicon-search\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \t</div>     \r\n");
      out.write("   <div class=\"col-md-3\">\r\n");
      out.write(" \t\r\n");
      out.write(" \t</div>     \r\n");
      out.write(" \r\n");
      out.write("     </div>\r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-default navbar-static-top\" role=\"navigation\" data-spy=\"affix\" data-offset-top=\"197\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"FinalJSP.jsp\">Home</a></li>\r\n");
      out.write("      <li><a href=\"category.jsp?param=Refrigerator\">Refrigerator</a></li>\r\n");
      out.write("      <li><a href=\"category.jsp?param=Iron\">Iron</a></li> \r\n");
      out.write("      <li><a href=\"category.jsp?param=Air Conditioner\">Air Conditioner</a></li>\r\n");
      out.write("      <li><a  href=\"category.jsp?param=Television\">Television</a></li> \r\n");
      out.write("       <li><a href=\"category.jsp?param=Mobile\">Mobile</a></li>\r\n");
      out.write("          <li><a href=\"category.jsp?param=Camera\">Camera</a></li>\r\n");
      out.write("             <li><a href=\"category.jsp?param=Pendrive\">Pendrive</a></li> \r\n");
      out.write("          <li><a href=\"category.jsp?param=Laptop\">Laptop</a></li>\r\n");
      out.write("          <li><a href=\"category.jsp?param=Earphones\">Earphones</a></li> \r\n");
      out.write("    </ul>\r\n");
      out.write("     <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"#\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModalforSignup\"  ><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("      <li><a class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\"  ><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-3 col-lg-3 col-md-3\">\r\n");
      out.write("                <p class=\"lead\"></p>\r\n");
      out.write("                <div class=\"list-group\"  style=\"margin-left: 20px;\">\r\n");
      out.write("                <h3>Trending Products</h3>\r\n");
      out.write("                               <div class=\"item active\" style=\"margin-toap: 10px\">\r\n");
      out.write("                                    <img src=\"http://placehold.it/800x300\" alt=\"\" width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img  src=\"http://placehold.it/800x300\" alt=\"\"width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img  src=\"http://placehold.it/800x300\" alt=\"\"width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img src=\"http://placehold.it/800x300\" alt=\"\"width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img  src=\"http://placehold.it/800x300\" alt=\"\"width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <img  src=\"http://placehold.it/800x300\" alt=\"\"width=\"80%\" height=\"50%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       <div class=\"col-md-9\">\r\n");
      out.write("            <div class=\"row\" >\r\n");
      out.write("           <a href=\"category.jsp?param=Refrigerator\"><h1>Refrigerator</h1></a>\r\n");
      out.write("           <div class=\"row\" id=\"fridge\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("            \r\n");
      out.write("              <div class=\"row\" >\r\n");
      out.write("           <a href=\"category.jsp?param=Iron\"><h1>Iron</h1></a>  \r\n");
      out.write("           \r\n");
      out.write("              <div class=\"row\" id=\"ac\">\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("                   \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("             <a href=\"category.jsp?param=Air Conditioner\"> <h1>Air Conditioner</h1></a>  \r\n");
      out.write("               <div class=\"row\" id=\"iron\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4\"></div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <p>Copyright &copy; www.goGrabIt.com 2016</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                    <div class=\"col-lg-4\"></div>\r\n");
      out.write("                 <!--  <div class=\"col-lg-4\">\r\n");
      out.write("                    <h3>Contact Us</h3>\r\n");
      out.write("                    <h4>Sanket Jain</h4>\r\n");
      out.write("                    <h5>+91-86575784856</h5>\r\n");
      out.write("                    <h5>05178-260840</h5>\r\n");
      out.write("                </div> -->\r\n");
      out.write("                 <!--  <div class=\"col-lg-6\">\r\n");
      out.write("                    <p>About Us</p>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
