/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-01-23 10:35:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psl.dao.CategoryDaoImpl;
import com.psl.dao.CategoryDao;
import java.util.Calendar;
import org.eclipse.jdt.internal.compiler.ast.ForeachStatement;
import java.util.List;
import java.util.Map;
import java.util.Set;
import com.psl.dao.ReviewDaoImpl;
import com.psl.bean.Review;
import com.psl.dao.ProductDaoImpl;
import com.psl.bean.Product;

public final class Review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");





      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>!!!...GOGrabIT...!!!</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jq.js\"></script>\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function getProductName(){\r\n");
      out.write("\t    \r\n");
      out.write("\t \r\n");

String name=(String)request.getParameter("param");
System.out.println(name);

ProductDaoImpl p=new ProductDaoImpl();
Product product=p.getProductByName(name);
CategoryDao categoryDao=new CategoryDaoImpl();

//String catName=product.getCategory().getCategoryName();

//System.out.println(catName);

System.out.println(product.getProductName());
System.out.println(product.getProductPrice());
String desc=product.getProductFeature();
double price=product.getProductPrice();

ReviewDaoImpl r=new ReviewDaoImpl();
int totalReview=r.getReviewById(product.getProductId());

List<Review> list=r.getReviewListbyProductId(product.getProductId());
Map<String,Review> reviewMap=r.getCustomernameByReview(list);
Calendar cal = Calendar.getInstance(); 
String[] months = {"January", "February",
		  "March", "April", "May", "June", "July",
		  "August", "September", "October", "November",
		  "December"};
Set<String> custnamelist=reviewMap.keySet();
for(String s :custnamelist){
	Review review=reviewMap.get(s);
	String d = review.getReviewDate().getDate()+" "+months[cal.get(review.getReviewDate().getMonth())];


      out.write("\r\n");
      out.write("$(\"#reviewsample\").append('<div class=\"well\"><label>'+\"");
      out.print(s);
      out.write("\"+'</label><h6>\t<label>'+\"");
      out.print(review.getReviewMessage());
      out.write("\"+'</label></h6><h6><label>'+\"");
      out.print(d);
      out.write("\"+'</label><a href=\"#\">Reply</a></h6></div>');\r\n");
      out.write("/* var newDiv;\r\n");
      out.write("newDiv = document.createElement(\"DIV\");\r\n");
      out.write("newDiv.innerHTML = html;\r\n");
      out.write("/*newDiv.id = \"field\" + itemID;\r\n");
      out.write("document.getElementById('fridge').insertBefore(newDiv,null); */\r\n");
}
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t/* $(\"#addreviewbuttom\").on(\"click\", function() {\r\n");
      out.write("\t\t \r\n");
      out.write("\t    $(\"#addreviewbuttom\").after('<div class=\"form-group\" ><label for=\"comment\" id=\"addReview\">Add Review:</label><textarea class=\"form-control\" rows=\"5\" id=\"comment\"></textarea><br><button type=\"button\" class=\"btn btn-primary\">Post Review</button>\t</div>');\r\n");
      out.write("\t    $(this).hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#addquesbuttom\").on(\"click\", function() {\r\n");
      out.write("\t\t \r\n");
      out.write("\t    $(\"#addquesbuttom\").after('<div class=\"form-group\" ><label for=\"comment\" id=\"addReview\">Ask Query:</label><textarea class=\"form-control\" rows=\"5\" id=\"comment\"></textarea><br><button type=\"button\" class=\"btn btn-primary\">Post Review</button>\t</div>');\r\n");
      out.write("\t    $(this).hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t */\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"getProductName()\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\twindow.fbAsyncInit = function() {\r\n");
      out.write("\t\t\tFB.init({\r\n");
      out.write("\t\t\t\tappId : '1098991976802112',\r\n");
      out.write("\t\t\t\txfbml : true,\r\n");
      out.write("\t\t\t\tversion : 'v2.5'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t(function(d, s, id) {\r\n");
      out.write("\t\t\tvar js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("\t\t\tif (d.getElementById(id)) {\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjs = d.createElement(s);\r\n");
      out.write("\t\t\tjs.id = id;\r\n");
      out.write("\t\t\tjs.src = \"//connect.facebook.net/en_US/sdk.js\";\r\n");
      out.write("\t\t\tfjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("\t\t}(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"myModalforSignup\" class=\"modal fade\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Header Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h2>Sign UP</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Body Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"First Name\" required autofocus /><br> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control input-lg\" placeholder=\"Last Name\"\r\n");
      out.write("\t\t\t\t\t\t\trequired /><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-lg\" placeholder=\"User Name\" required /><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Contact No\" required /><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-lg\" placeholder=\"Email\" required /><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Password\" required /><br> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"password\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Confirm Password\" required /><br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\">Sign Up</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal for sign in -->\r\n");
      out.write("\t<div id=\"myModal\" class=\"modal fade\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Header Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h2>Please sign in</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"fb-login-button\" data-max-rows=\"1\" data-size=\"large\"\r\n");
      out.write("\t\t\t\t\t\tdata-show-faces=\"false\" data-auto-logout-link=\"false\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Body Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control input-lg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Email\" required autofocus /> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-lg\" placeholder=\"Password\" required />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"remember-me\" /> Remember me\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\">Sign In</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer Section -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"pull-left\"><a href=\"#\">Forgot Password?</a></span> <span><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">Register</a></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" width=\"30%\" height=\"30%\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-search\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"FinalJSP.jsp\">Home</a></li>\r\n");
      out.write("      <li><a href=\"category.jsp?param=Refrigerator\">Refrigerator</a></li>\r\n");
      out.write("      <li><a href=\"category.jsp?param=Iron\">Iron</a></li> \r\n");
      out.write("      <li><a href=\"category.jsp?param=Air Conditioner\">Air Conditioner</a></li>\r\n");
      out.write("      <li><a  href=\"category.jsp?param=Television\">Television</a></li> \r\n");
      out.write("       <li><a href=\"category.jsp?param=Mobile\">Mobile</a></li>\r\n");
      out.write("          <li><a href=\"category.jsp?param=Camera\">Camera</a></li>\r\n");
      out.write("             <li><a href=\"category.jsp?param=Pendrive\">Pendrive</a></li> \r\n");
      out.write("          <li><a href=\"category.jsp?param=Laptop\">Laptop</a></li>\r\n");
      out.write("          <li><a href=\"category.jsp?param=Earphones\">Earphones</a></li> \r\n");
      out.write("    </ul>\r\n");
      out.write("     <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"#\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModalforSignup\"  ><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("      <li><a class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\"  ><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12 \">\r\n");
      out.write("\t\t\t\t<!-- col-md-12 col-sm-12 -->\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<label><h4>Name of Catagory</h4>></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img  src=\"images/");
      out.print(name);
      out.write(".jpeg\" alt=\"\" id=\"fridges\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"caption\" id=\"captionreviewid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2 id=\"pname\" >");
      out.print(name );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h4>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"caption\" ><h4>Price:  ");
      out.print(price );
      out.write("</h4></div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ratings\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-star\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-star\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-star\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-star\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-star\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>");
      out.print(totalReview );
      out.write(" reviews</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4  id=\"captionreviewid\">");
      out.print(desc );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#addReview\"><button id=\"addreviewbuttom\" type=\"button\"  class=\"btn btn-primary\">Add\r\n");
      out.write("\t\t\t\t\t\t\t\t\tReview</button></a>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#addQues\">\t\t<button  id=\"addquesbuttom\" type=\"button\" class=\"btn btn-primary\">Ask Query</button></a>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">Reviews & Queries</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 id=\"addr\">Reviews</h4><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"reviewsample\" class=\"well\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"comment\" id=\"addReview\">Add Review:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" id=\"comment\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Post\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tReview</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Queries</h4><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"comment\" id=\"addQues\">Ask Query:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" id=\"comment\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Post\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tQuery</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 col-md-9  col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<h1>Name of product</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<p>Copyright &copy; www.goGrabIt.com 2016</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\r\n");
      out.write("\t\t\t\t<!--  <div class=\"col-lg-4\">\r\n");
      out.write("                    <h3>Contact Us</h3>\r\n");
      out.write("                    <h4>Sanket Jain</h4>\r\n");
      out.write("                    <h5>+91-86575784856</h5>\r\n");
      out.write("                    <h5>05178-260840</h5>\r\n");
      out.write("                </div> -->\r\n");
      out.write("\t\t\t\t<!--  <div class=\"col-lg-6\">\r\n");
      out.write("                    <p>About Us</p>\r\n");
      out.write("                </div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
